### ISSUE TITLE
(lucas)Artefactos de Scrum: 3 herramientas claves

### ISSUE THREAD

**Issue by ezeq81** [Lu-deng/ISPC---TSDWAD-#13]
Explicación de las 3 herramientas claves

**Comment by Almironlucas** [comment]
ARTEFACTOS DE SCRUM: 3 HERRAMIENTAS CLAVES
Son las herramientas  o elementos que se utilizan para el registro de la informacion necesaria, y para garantizar la trnsparencia del proceso.
1. Product backlog: Pila del producto. Requisitos globales del producto a desarrollar. El Product backlog es lista ordenada de lo que se necesita mejorar del producto.
2. Sprint backlog: Pila del sprint. La parte del product backlog a realizar en un sprint. Es un plan realizado por y para los developers. Se actualiza a lo largo del Sprint, a medida que se aprende mas.
3. Incremento: es el resultado que se obtiene de cada sprint. Es un peldaño concreto hacia el objetivo del producto.
