### ISSUE TITLE
(Lucas)Ventajas de la metodología Scrum

### ISSUE THREAD

**Issue by Lu-deng** [Lu-deng/ISPC---TSDWAD-#14]

**Comment by Almironlucas** [comment]
Las principales ventajas de la metodología SCRUM:
1. Dimensiona los proyectos de manera correcta gracias a que los bloques de trabajo son mucho más pequeños, se logra una gestion mucho más eficiente de todos los flujos de trabajo.
Mediante la división en interaciones o sprints es mas sencilla la identificacion de los objetivos y de los posibles contratiempos a los que nos vamos a tener que enfrentar.
2. El equipo, en constante aprendizaje: No es necesario esperar a la finalización del proyecto para darnos cuenta de los errores, sino que podemos ir aprendiendo y corrigiendo los mismos según se lleva a cabo el mismo.
3. Imprime una mayor flexibilidad: En un entorno como el actual, la flexibilidad se ha consolidado como uno de los valores más perseguidos por las empresas. La capacidad para adaptarse a los diferentes contextos que pueden ir emergiendo durante todo el proyecto puede ser un factor fundamental en el resultado final del mismo.
La metodología SCRUM permite ser mucho más reactivo a cualquier tipo de cambio o situación que pueda emerger.
