### ISSUE TITLE
GITHUB Issues

### ISSUE THREAD

**Issue by MelaniAguero** [Lu-deng/ISPC---TSDWAD-#6]
Explica en resumen su funcionamiento para que y cuando usarlas

**Comment by VictoriaTSDW** [comment]
Perfecto!

**Comment by VictoriaTSDW** [comment]
mi duda es, resuelvo la issue y genero un nuevo read me con la definición? Entiendo que este cuadro es para comentarios relativos a la issue no estoy segura de que sea para pegar aquí mismo el concepto...

DEFINICIÓN ISSUE (concepto extraído de "Github" - Resumen de GitHub, material de la cátedra.
Un issue en GitHub es una unidad de trabajo designada para realizar una mejora en un sistema informático. Puede  ser el arreglo de un fallo, una característica pedida, una tarea, una solicitud de documentación en específico y todo tipo de ideas o sugerencias al equipo de desarrollo. 
Una unidad de trabajo o tarea, se crea completando con un título (obligatorio) y una descripción. Si la persona es miembro del equipo, opcionalmente puede asignar una serie de metadatos: etiquetas (labels), hitos (milestone), proyecto al que pertenece o responsables encargados de cerrar la incidencia.
Una vez creado, se asignará un número.
